ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS starting_point TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS ending_point TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS departure_time TIMESTAMPTZ;
